"""empty message

Revision ID: 2c00e9ec2208
Revises: 1e71641c60a5
Create Date: 2026-04-28 03:42:44.070352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c00e9ec2208'
down_revision = '1e71641c60a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_hora', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('foto_url', sa.String(length=300), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('foto_url')
        batch_op.drop_column('precio_hora')

    # ### end Alembic commands ###
