"""empty message

Revision ID: 2e932b78a864
Revises: 654b862eaa07
Create Date: 2026-04-23 03:16:35.126098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e932b78a864'
down_revision = '654b862eaa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('complejo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['complejo_id'], ['complejo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complejo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('google_map', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complejo', schema=None) as batch_op:
        batch_op.drop_column('google_map')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    op.drop_table('cancha')
    # ### end Alembic commands ###
