"""empty message

Revision ID: 8da7ee630f8a
Revises: 2c00e9ec2208
Create Date: 2026-04-28 04:09:07.930160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da7ee630f8a'
down_revision = '2c00e9ec2208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=20), nullable=False),
    sa.Column('hora', sa.String(length=10), nullable=False),
    sa.Column('es_bloqueo', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cancha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cancha_id'], ['cancha.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_apertura', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('hora_cierre', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancha', schema=None) as batch_op:
        batch_op.drop_column('hora_cierre')
        batch_op.drop_column('hora_apertura')

    op.drop_table('reservas')
    # ### end Alembic commands ###
