"""empty message

Revision ID: e86f6182a225
Revises: 6e9f06f8e642
Create Date: 2026-05-08 19:22:17.145410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86f6182a225'
down_revision = '6e9f06f8e642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('monto_pagado', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('monto_pagado')
        batch_op.drop_column('precio_total')

    # ### end Alembic commands ###
